
import os
import sys

from typing import Any

import pyvista as pv
import numpy as np

import util


class SkeletonPlayer:
    """
    This is an element that can be used to show the tracks generated by the
    developed tracking system in a 3d visualization.
    """

    def __init__(self, cameras: list, frames: list, fps: float, center=(0, 0, 0), up=(0, 1, 0)):
        self.fps = fps
        self.frames = frames
        self.current_frame = 0
        self.is_playing = False
        self.track_meshes = {}
        self.track_actors = {}
        # Setup the plotter. (Launder the type though Any to avoid wrong errors.)
        plotter: Any = pv.Plotter()
        self.pl = plotter
        self.pl.add_axes()
        self.pl.set_background("white")
        # Precompute skeleton topology.
        lines = []
        for p1, p2 in util.SKELETON:
            lines.extend([2, p1, p2])
        self.skeleton = np.array(lines)
        # Setup the scene and draw the first frame.
        self.setup_ground(center, up)
        self.setup_cameras(cameras)
        self.setup_widgets()
        self.update_scene(0)

    def setup_ground(self, center: tuple[float, float, float], up: tuple[float, float, float]):
        ground = pv.Plane(
            center=center, direction=up, i_size=10,
            j_size=10, i_resolution=20, j_resolution=20
        )
        self.pl.add_mesh(ground, style="wireframe", color="lightgray")

    def setup_cameras(self, cameras: list, scale=0.5):
        for cam in cameras:
            rotation = np.array(cam["R"])
            translate = np.array(cam["t"]).flatten()
            camera_center = -rotation.T @ translate
            intrinsics = np.array(cam["K"])
            fx, fy = intrinsics[0, 0], intrinsics[1, 1]
            cx, cy = intrinsics[0, 2], intrinsics[1, 2]
            width, height = cx * 2, cy * 2
            z_cam = scale
            x0 = (0 - cx) * z_cam / fx
            x1 = (width - cx) * z_cam / fx
            y0 = (0 - cy) * z_cam / fy
            y1 = (height - cy) * z_cam / fy
            corners_cam = np.array([
                [x0, y0, z_cam], [x1, y0, z_cam],
                [x1, y1, z_cam], [x0, y1, z_cam]
            ])
            corners_world = (corners_cam @ rotation) + camera_center
            vertices = np.vstack([camera_center, corners_world])
            lines = np.array([
                [2, 0, 1], [2, 0, 2], [2, 0, 3], [2, 0, 4],
                [2, 1, 2], [2, 2, 3], [2, 3, 4], [2, 4, 1]
            ]).flatten()
            camera_wireframe = pv.PolyData(vertices, lines=lines)
            self.pl.add_mesh(camera_wireframe, color="black", line_width=2)
            self.pl.add_mesh(
                pv.Sphere(radius=scale * 0.05, center=camera_center), color="red")

    def get_or_create_track(self, track_id):
        if track_id not in self.track_meshes:
            mesh = pv.PolyData()
            color = util.COLORS[track_id % len(util.COLORS)]
            actor = self.pl.add_mesh(
                mesh, color=color,
                render_lines_as_tubes=True, line_width=8,
                render_points_as_spheres=True, point_size=15,
                smooth_shading=True
            )
            self.track_meshes[track_id] = mesh
            self.track_actors[track_id] = actor
        return self.track_meshes[track_id], self.track_actors[track_id]

    def update_scene(self, value):
        frame_idx = int(np.round(value))
        if frame_idx >= len(self.frames):
            frame_idx = len(self.frames) - 1
        self.current_frame = frame_idx
        # Hide all tracks.
        for actor in self.track_actors.values():
            actor.SetVisibility(False)
        # Update and show all tracks visible at this time step.
        for track in self.frames[self.current_frame]:
            new_mesh = pv.PolyData(np.array(track["kpts"]))
            new_mesh.lines = self.skeleton
            mesh, actor = self.get_or_create_track(track["id"])
            mesh.copy_from(new_mesh)
            actor.SetVisibility(True)

    def toggle_play(self):
        self.is_playing = not self.is_playing

    def timer_callback(self, step):
        if self.is_playing:
            self.next_frame()

    def next_frame(self):
        next_frame = (self.current_frame + 1) % len(self.frames)
        self.slider.GetRepresentation().SetValue(next_frame)
        self.update_scene(next_frame)
        self.pl.render()

    def prev_frame(self):
        prev_frame = (self.current_frame - 1) % len(self.frames)
        self.slider.GetRepresentation().SetValue(prev_frame)
        self.update_scene(prev_frame)
        self.pl.render()

    def setup_widgets(self):
        self.slider = self.pl.add_slider_widget(
            callback=self.update_scene, rng=[0, len(self.frames) - 1], value=0,
            pointa=(0.1, 0.03), pointb=(0.9, 0.03), style="modern",
            interaction_event="always"
        )
        self.pl.add_timer_event(
            max_steps=1000000, duration=1000/self.fps, callback=self.timer_callback)
        self.pl.add_key_event("space", self.toggle_play)
        self.pl.add_key_event("Right", self.next_frame)
        self.pl.add_key_event("Left", self.prev_frame)

    def show(self):
        """ Show the plotter by opening the window. """
        self.pl.show()


if __name__ == "__main__":
    if len(sys.argv) <= 1 or not os.path.isfile(sys.argv[1]):
        print("", file=sys.stderr)
        exit(1)
    cams, frames, fps, center, up = util.load_tracks(sys.argv[1])
    player = SkeletonPlayer(cams, frames, fps, center, up)
    player.show()
